version: "3.7"

x-default-envvars: &default-envvars
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PASS: ${DB_PASS}
  DJANGO_SETTINGS_MODULE: settings.develop

x-default-dbvars: &default-dbvars
  <<: *default-envvars
  MYSQL_DATABASE: ${DB_NAME}
  MYSQL_ROOT_PASSWORD: ${DB_PASS}

x-default-app: &default-app
  build:
    .
  volumes:
    - ./src:/app
    - .env:/app/.env
  environment:
    <<: *default-envvars


services:
  app:
    <<: *default-app
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - django-starter-db:/var/lib/postgresql/data
    environment:
      <<: *default-dbvars

  redis:
    image: redis:latest
    ports:
     - "6379:6379"

volumes:
  django-starter-db:
